# Generated by Django 5.0.1 on 2024-02-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_read_groupmessage_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='read',
            new_name='is_read',
        ),
    ]
