# Generated by Django 5.0.1 on 2024-02-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_read_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='delivery_status',
        ),
    ]
